In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

#one_hot 独热编码，也叫一位有效编码。在任意时候只有一位为1，其他位都是0
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

train_images = mnist.train.images
train_labels = mnist.train.labels
test_images = mnist.test.images
test_labels = mnist.test.labels

print("train_images_shape:", train_images.shape)
print("train_labels_shape:", train_labels.shape)
print("test_images_shape:", test_images.shape)
print("test_labels_shape:", test_labels.shape)
print("train_images:", train_images[0])
print("train_images_length:",len(train_images[0]))
print("train_labels:", train_labels[0])


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
train_images_shape: (55000, 784)
train_labels_shape: (55000, 10)
test_images_shape: (10000, 784)
test_labels_shape: (10000, 10)
train_images: [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.     

In [2]:
import tensorflow as tf
import numpy as np

#占位符，适用于不知道具体参数的时候
x = tf.placeholder(tf.float32, shape=(4, 4))
y = tf.add(x, x)
# [1,  32, 44, 56]
# [89, 12, 90, 33]
# [35, 69, 1,  10]
argmax_paramter = tf.Variable([[1, 32, 44, 56], [89, 12, 90, 33], [35, 69, 1, 10]])

#最大列索引
argmax_0 = tf.argmax(argmax_paramter, 0)
#最大行索引
argmax_1 = tf.argmax(argmax_paramter, 1)

#平均数
reduce_0 = tf.reduce_mean(argmax_paramter, reduction_indices=0)
reduce_1 = tf.reduce_mean(argmax_paramter, reduction_indices=1)

#相等
equal_0 = tf.equal(1,2)
equal_1 = tf.equal(2,2)

#类型转换
cast_0 = tf.cast(equal_0,tf.int32)
cast_1 = tf.cast(equal_1,tf.float32)

with tf.Session() as sess:
    init = tf.global_variables_initializer();
    sess.run(init)
    
    rand_array = np.random.rand(4, 4)
    print(sess.run(y, feed_dict={x: rand_array}))

    print("argmax_0:", sess.run(argmax_0))
    print("argmax_1:", sess.run(argmax_1))
    print("reduce_0:", sess.run(reduce_0))
    print("reduce_1:", sess.run(reduce_1))
    print("equal_0:", sess.run(equal_0))
    print("equal_1:", sess.run(equal_1))
    print("cast_0:", sess.run(cast_0))
    print("cast_1:", sess.run(cast_1))

[[0.8764925  0.00947174 0.5768155  0.28432593]
 [1.5949831  0.43149847 1.5539443  0.02548405]
 [0.59853387 0.07296697 1.3697519  1.2248737 ]
 [1.5166551  1.158773   1.2052476  0.24650799]]
argmax_0: [1 2 1 0]
argmax_1: [3 2 1]
reduce_0: [41 37 45 33]
reduce_1: [33 56 28]
equal_0: False
equal_1: True
cast_0: 0
cast_1: 1.0


In [3]:
import tensorflow as tf

# 导入数据集
# from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

# 变量
batch_size = 100

#训练的x(image),y(label)
# x = tf.Variable()
# y = tf.Variable()
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 模型权重
#[55000,784] * W = [55000,10]
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

# 用softmax构建逻辑回归模型
pred = tf.nn.softmax(tf.matmul(x, W) + b)

# 损失函数(交叉熵)
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(pred), 1))

# 低度下降
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

# 初始化所有变量
init = tf.global_variables_initializer()

# 加载session图
with tf.Session() as sess:
    sess.run(init)

    # 开始训练
    for epoch in range(25):
        avg_cost = 0.
        
        total_batch = int(mnist.train.num_examples/batch_size)
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(optimizer, {x: batch_xs,y: batch_ys})
            #计算损失平均值
            avg_cost += sess.run(cost,{x: batch_xs,y: batch_ys}) / total_batch
        if (epoch+1) % 5 == 0:
            print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(avg_cost))

    print("运行完成")

    # 测试求正确率
    correct = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))
    print("正确率:", accuracy.eval({x: mnist.test.images, y: mnist.test.labels}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0005 cost= 0.463781533
Epoch: 0010 cost= 0.390949408
Epoch: 0015 cost= 0.361387678
Epoch: 0020 cost= 0.344145836
Epoch: 0025 cost= 0.332440977
运行完成
正确率: 0.914
